image: docker

services:
  - docker:dind

before_script:
  - export
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
build:
  script:
    - docker build --tag registry.gitlab.com/ershov.a/flatris:latest --tag registry.gitlab.com/ershov.a/flatris:$CI_COMMIT_SHA .
    - docker push registry.gitlab.com/ershov.a/flatris:latest
    - docker push registry.gitlab.com/ershov.a/flatris:$CI_COMMIT_SHA
